language: php

branches:
  only:
    - develop
    
install:
  - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
  - travis_retry composer global require phpunit/phpunit ^5

script:
  - /home/travis/.composer/vendor/bin/phpunit --no-coverage
